<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>oomwoo_rose2</name>
  <version>0.1.0</version>
  <description>ROS 2 port of ROSE and ROSE2 room segmentation.</description>
  <maintainer email="dev@example.com">oomwoo</maintainer>
  <license>GPL-3.0-only</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>oomwoo_segmentation</exec_depend>
  <exec_depend>oomwoo_segmentation_interfaces</exec_depend>
  <exec_depend>python3-descartes</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>
  <exec_depend>python3-networkx</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-pil</exec_depend>
  <exec_depend>python3-png</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-shapely</exec_depend>
  <exec_depend>python3-skimage</exec_depend>
  <exec_depend>python3-sklearn</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
