oomwoo_rose2:
  ros__parameters:
    action_name: /room_segmentation/segment
    filter_level: 0.18
    fft_peak_height: 0.2
    fft_band_width: 50
    spatial_clustering_line_segments_threshold: 5.0
    lines_threshold: 0.22
    lines_distance_px: 20.0
    edges_threshold: 0.0
    hard_wall_threshold: 0.40
    min_component_size: 10
    enable_geodesic_coverage: true
    rooms_voronoi: false
    voronoi_closeness: 10
    voronoi_blur: 8
    voronoi_iterations: 5
